### ISSUE TITLE
cordova-android 7.0.0

### ISSUE THREAD

**Issue by oborudko** [ionic-team/ionic-plugin-deeplinks#139]
it seems the plugin is not compatible with cordova-android 7.0.0 (https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)

`Failed to install 'ionic-plugin-deeplinks': Error: ENOENT: no such file or directory, open '...../platforms/android/AndroidManifest.xml'
`

from the cordova announcement it seems like the plugin.xml needs to be altered, right or I am getting it wrong

**Comment by jawad-aziz-farhad** [comment]
Facing same issue. @oborudko  you found any solution ?

**Comment by oborudko** [comment]
well solution is either to make a fork and fix it (since the ionic-deeplinks is not longer maintained) or just stick to android 6, which is what I did for now.

**Comment by mirko77** [comment]
I would be curious to know why all the libraries dealing with deep linking get abandoned after a while.

Is it that difficult and time consuming the get something working properly?

**Comment by mlynch** [comment]
Update here, I just added a community maintainer and so some of these issues can get addressed. Let me know if you're interested in helping and I can add anyone else.

As for why these things get abandoned, what looks like a simple problem ends up having tons of edge cases or features that folks want. Also apple and google change their deep linking approaches constantly. Makes it harder to keep up for something that has stronger alternatives (like Branch), but hopefully the community help can fix that!
