### ISSUE TITLE
NO LONGER MAINTAINED?

### ISSUE THREAD

**Issue by Harshakvarma** [ionic-team/ionic-plugin-deeplinks#143]
# Can anyone say why this is "NO LONGER MAINTAINED"

Does BranchMetrics plugin works without me using their offering? I just need deep linking to my ionic1 app

**Comment by mlynch** [comment]
It's not maintained because we don't have the resources to work on it. However, we would gladly have a maintainer to help or promote a fork of it in the future. Also, our [Capacitor](http://capacitor.ionicframework.com/) project has some basic deeplinking built in.
