### ISSUE TITLE
Deeplinking doesn't work when app is cold start on iOS

### ISSUE THREAD

**Issue by rajkumar-osm** [ionic-team/ionic-plugin-deeplinks#150]
When I debugged the code, it seems like the following line is being true when the app is opened  after killing it completely.
https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L23

Because of this, this line doesn't get triggered 
https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/IonicDeeplinkPlugin.m#L38

**Comment by rajkumar-osm** [comment]
It's specific to my project, so I will dig out the problem.

**Comment by colonelpopcorn** [comment]
@rajkumar-osm Did you solve this issue? I'm running into similar problems in my project.
