### ISSUE TITLE
when app is open, deeplink not working.

### ISSUE THREAD

**Issue by AmyJUn** [ionic-team/ionic-plugin-deeplinks#166]
hi,

my app uses deeplink to find some pages through the email link.

it is alright with cold start in android 7.1.1 

but once the app is opened,  deeplink is not working. I have upgraded many things for this like android, angular, typescript....

i put the code in ngAfterViewInit before and change to constructor both not working and i register provider in app.module.ts

any idea?

this.platform.ready().then(() => {
            this.deeplinks.route({
                '/about-us': AboutPage,
                '/longform/id=:productId': WctPage
            }).subscribe(match => {
                alert('Successfully routed'+ match);
                alert(NgZone.isInAngularZone()); // false
                this.ngZone.run(() => {
                    alert(NgZone.isInAngularZone()); // true
                    this.nav.push(match.$route);
                });
            }, nomatch => {
                alert('Unmatched Route'+ nomatch);
            });
        })

`Ionic:

   ionic (Ionic CLI)  : 4.3.0 (C:\Users\AmyJun\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-webview 2.2.0, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\AmyJun\AppData\Local\Android\Sdk)
   NodeJS            : v6.14.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.3.0
   OS                : Windows 10

`

**Comment by proofles** [comment]
i have same issue. Did you find any solution?
