### ISSUE TITLE
Incompatible with cordova-ios v5.0.0 ?

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic-plugin-deeplinks#176]
# Bug Report

## Problem
With cordova ios v5.0.0 the app would still popup (generally listening fine to `URL_SCHEME` - however, once the app has focus the plugin **which works just fine with v4.5.5** is not receiving the  callback.

### What is expected to happen?
v5.0.0 should work the same as v4.5.5 and not only launch the app, but also "forward" the URI/path as it used to.

### What does actually happen?
The app is getting focus, but the callback is never made to pass on the URI/path:
`myapp://open/some/page`
`open/some/page` is never received by the deeplink plugin callback.

### Command or Code
I've been using your sites simple example.

Crosslinking to cordova-ios https://github.com/apache/cordova-ios/issues/532

**Comment by olivermuc** [comment]
The  cordova-ios team already shed more light on the issue (see cross lonk above), and while it looks fairly doable what they are suggesting, it's still beyond my front end coding skills.

Hello community :) ...help!

**Comment by olivermuc** [comment]
I believe I fixed it, PR on its way.

**Comment by Farmertjes** [comment]
@olivermuc I took your PR and added backwards compatibility. https://github.com/ionic-team/ionic-plugin-deeplinks/pull/178

**Comment by alexyazvinsky** [comment]
When will it be merged and released?

**Comment by dcxn** [comment]
Thank you very much for your efforts so far guys. Are there any updates on this? 
Compatibility with **cordova-ios 5.0.0** is needed due to the iOS 12.1 SDK build app store requirement coming into effect this week.

**Comment by chrisweight** [comment]
I've merged in the latest PR that looks to solve this and a few other issues and will issue a rollup release in a minute
