### ISSUE TITLE
Ionic V4 - 'Deeplinks' refers to a value, but is being used as a type here

### ISSUE THREAD

**Issue by Silverbug** [ionic-team/ionic-plugin-deeplinks#197]
After installing the deeplinks package and adding it to one of my components 
In my constructor I have:  

```
import { Deeplinks } from '@ionic-native/deeplinks';

....

  constructor(
    ...
    private deeplink: Deeplinks
  ) {
```

But am getting the following error in VSCode:

`'Deeplinks' refers to a value, but is being used as a type here`

When I run ionic serve i get:

`ERROR in src/app/app.component.ts(68,23): error TS2304: Cannot find name 'Deeplinks'.`

I'm currently running ionic v4 & "@ionic-native/deeplinks": "^5.8.0",

Happy to provide anymore info if it helps. Google didn't provide much in the way of solutions.

**Comment by hyeritsyan** [comment]
Hi, I think your issue might be solved using this in your import line:

`import { Deeplinks } from '@ionic-native/deeplinks/ngx';`

**Comment by Silverbug** [comment]
Yeah that was it, I'm going to spend some time getting it working now that i've got past this bug.

Someone may want to update the documentation on the ionic site to include that in there :)
