### ISSUE TITLE
App relaunches when deeplink is clicked[Android]

### ISSUE THREAD

**Issue by RobinGiel** [ionic-team/ionic-plugin-deeplinks#207]
When clicking on a deeplink or redirecting the deeplink to my app to app relaunches. 
I'm guessing this has to with Main.activity being called. Or getting the intent without any flags.

https://github.com/ionic-team/ionic-plugin-deeplinks/blob/0eaf00eee43405c50db8328fd314e476e8a9383b/src/android/io/ionic/links/IonicDeeplink.java#L52-L77

**Comment by JacoRoos** [comment]
@RobinGiel I don't know if this is still an issue for you, but you may want to double check the Android setup documentation:
"To prevent Android from creating multiple app instances when opening deeplinks, you can add the following preference in Cordova config.xml file: <preference name="AndroidLaunchMode" value="singleTask" />"

**Comment by RobinGiel** [comment]
Thanks for the reply @JacoRoos
