### ISSUE TITLE
iOS14 AppTrackingTransparency

### ISSUE THREAD

**Issue by gatelli** [ionic-team/ionic-plugin-deeplinks#246]
Hi,
It seems your plugin uses IDFA so it requires a message asking users for their device UUID use, as for advertisements, or Apple rejects the app.
Does this use is absolutely required by the plugin ? Is there a way to remove that ?
Thanks !

**Comment by jpike88** [comment]
Where in the iOS code is IDFA being use?

**Comment by gatelli** [comment]
IonicDeeplinkPlugin.m lines 126-151

**Comment by jpike88** [comment]
Wtf!

@elylucas can you please explain this, this could get app devs punished for no good reason.

**Comment by Sayene** [comment]
looks like IonicDeeplinkPlugin.m lines 126-151 and line 12 in IonicDeeplinkPlugin.h can be safely removed, without any damage to the plugin functionality

**Comment by joeldhenry** [comment]
who can accept the PR?

**Comment by joeldhenry** [comment]
@mlynch can you publish this change to NPM as version 1.0.23?

**Comment by mlynch** [comment]
@joeldhenry done! Live in 1.0.23

**Comment by joeldhenry** [comment]
thanks so much!
