### ISSUE TITLE
Deeplinks.routeWithNavController doesn't work without subscribe

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-plugin-deeplinks#34]
Hey,

Maybe I misunderstand the readme/documentation, but I noticed that using Deeplinks.routeWithNavController without subscribing to the results won't gonna work.

What I mean is that following piece of code didn't worked for me:

```
Deeplinks.routeWithNavController(this.navController, {
   '/about-us': AboutPage,
   '/products/:productId': ProductPage
});
```

Where that worked

```
Deeplinks.routeWithNavController(this.navController, {
   '/about-us': AboutPage,
   '/products/:productId': ProductPage
}).subscribe((match) => {
    console.log('Successfully matched route', match);
    }, (nomatch) => {
    console.error('Got a deeplink that didn\'t match', nomatch);
    });
```

Again thx for the cool plugin ;)

**Comment by mlynch** [comment]
Ah, hmm. This is an issue we've ran into with ionic native in general, not sure how best to make the observable "trigger" without listening to it...will think on this a bit

**Comment by peterpeterparker** [comment]
I'm agree with you. I just wanted to point out, that the readme / documentation

https://github.com/driftyco/ionic-plugin-deeplinks

doesn't display explicitly that Deeplinks.routeWithNavController return a promise. Therefore I just wanted to suggest to update the documentation.

Nothing more nothing less ;)

**Comment by jguix** [comment]
I agree, I proposed a change in Ionic Native documentation to show that.

**Comment by mlynch** [comment]
Thanks, updated the readme to reflect this
