### ISSUE TITLE
AndroidManifest.xml not updating $DEEPLINK_HOST value

### ISSUE THREAD

**Issue by theaccordance** [ionic-team/ionic-plugin-deeplinks#38]
Plugin Version: 1.0.8
Cordova CLI: 6.2.0
Android Platform Version: 5.2.0

Noticed an inconsistency in with how `$DEEPLINK_HOST` is set in `AndroidManifest.xml`. When building from scratch (no previous build exists in `platforms/android`), the value is properly set, but when a previous build exists, the value isn't updated, but other values in the manifest are being updated (`android:versionCode`, `android:versionName`, etc.).  

Perhaps it's a missing hook?

**Comment by yargomascarenhas** [comment]
This issue is a cause of this error in "ionic run android", Error: Cannot read property 'forEach' of undefined
