### ISSUE TITLE
Random blank screen in ios9(iphone4)

### ISSUE THREAD

**Issue by grapemix** [ionic-team/ionic-plugin-deeplinks#50]
Hi,

Thanks for this plugin and the blog post. We are experiencing a weird bug: a black screen after routing successfully **iff the app has not been started**. These problem only shows in iphone4(ios9) but not android devices nor ios10 iphone6. The deeplink is triggered by custom scheme.

In our use case, we must share our links into following pattern: SCHEME://HOST_NAME/share?param1=value&param2=value2 instead of SCHEME://HOST_NAME/share/:param1/:param2 or the others.

So we have to come up a config like this:
      Deeplinks.route({
        '/share': TelegramDetailPage,
      })
      .subscribe(
        (match) => {
          console.log('Successfully routed', match);
          if("tid" in match.$args)
            this.nav.push(detailPage, match.$args);
          else if("cid" in match.$args)
            this.nav.push(anotherPage, match.$args);
          else
            this.nav.push(ProfilePage, match.$args);
        }, 
        (nomatch) => {
          console.warn('Unmatched Route', nomatch);
      });

The Component is loaded, data is fetched and everything seems working except showing the white/black screen randomly. We can even click the link to go to another page. If the app has been already started, everything is fine too. We are so lost because there has no error/debug message. We have tested on android and ios devices. Can you please give us some hints?

Ty.

**Comment by mlynch** [comment]
Can you see if there's any console output or errors or anything?
